spring.application.name=cabeleleila

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true

app.admin.senha=leila2026
app.admin.token=cabeleleila-admin-token

app.salao.nome=Cabeleleila Leila
app.salao.telefone=(85) 3222-1000

server.port=${PORT:8080}